name: Deploy to cloudtype
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: raymondanythings/ms-messenger
          stage: dev
          yaml: |
            name: emochat-server-dev
            app: node@16
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: CLIENT_URL
                  secret: CLIENT_URL
                - name: DB_HOST
                  secret: DB_HOST
                - name: DB_NAME
                  secret: DB_NAME
                - name: DB_PORT
                  secret: DB_PORT
                - name: DB_PWD
                  secret: DB_PWD
                - name: DB_USER
                  secret: DB_USER
              ports: "4000"
              install: yarn
              build: yarn build
              start: yarn start:prod
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}